name: .NET Framework Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest

    env:
      Solution_Name: WpfApp4.sln
      Project_Folder: WpfApp1
      Platform: x64
      Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:RestorePackagesConfig=true /p:Configuration=$env:Configuration /p:Platform=$env:Platform
      
    - name: Build the application
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform=$env:Platform

    - name: Zip Artifacts
      uses: papeloto/action-zip@v1
      with:
        files: WpfApp1\bin\Release\
        dest: result.zip
        
    - name: notification
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: 837464295:AAFDLPRgeF5IxjLWpvaE9RGq0MO2BaK2CGo
        chatId: 385476257
        
    - name: send photo message
      uses: appleboy/telegram-action@master
      with:
        to: 385476257
        token: 837464295:AAFDLPRgeF5IxjLWpvaE9RGq0MO2BaK2CGo
        message: send photo message
        document: result.zip
